### ISSUE TITLE
关于clip_model.encode_text中attn_mask维度不匹配

### ISSUE THREAD

**Issue by Keinitial** [Event-AHU/OpenPAR#1]
您好，请问您知道我这是哪里出问题了吗，提示clip_model.encode_text中attn_mask维度不匹配。self.text = clip.tokenize(attributes).to("cuda")    后的维度(attr_num, 77)。感谢您的注意！
![question](https://github.com/Event-AHU/OpenPAR/assets/46866971/765a07cf-86f4-4e56-a427-ca35b6429ec3)

**Comment by 1125178969** [comment]
你好， 这是我们疏忽导致的一个bug，当缺少参数--use_text_prompt时会出现这个问题， 我们现在更新了代码，已经修复这个问题

**Comment by Keinitial** [comment]
> 你好， 这是我们疏忽导致的一个bug，当缺少参数--use_text_prompt时会出现这个问题， 我们现在更新了代码，已经修复这个问题

好的，感觉您的回复！
