### ISSUE TITLE
about the visualization of the feature map

### ISSUE THREAD

**Issue by Keinitial** [Event-AHU/OpenPAR#17]
May I ask if it is possible to open source code related to visualization of the feature map？

**Comment by 1125178969** [comment]
You can refer to the vit_explain code, which we also modified based on it

**Comment by 1125178969** [comment]
Currently uploaded pre-trained model for RAP1 dataset, and other datasets will be uploaded at my leisure

**Comment by Keinitial** [comment]
Thanks！
