### ISSUE TITLE
Add code for finetuning

### ISSUE THREAD

**Issue by cs-mshah** [Event-AHU/OpenPAR#21]
Hi,
Thanks for this amazing repository. It would be really helpful if you could release code for finetuning a pre-trained model on a custom dataset having different number of attributes. Can you also release model checkpoints?

**Comment by 1125178969** [comment]
We have updated the checkpoint information for the relevant datasets, and the fine-tuning code for custom datasets with different numbers of attributes will be updated later.

**Comment by Nouman945** [comment]
> Hi, Thanks for this amazing repository. It would be really helpful if you could release code for finetuning a pre-trained model on a custom dataset having different number of attributes. Can you also release model checkpoints?

Were you able to download the checkpoints. And can you share them over the Google Drive please? I am trying but I cannot create a account for baidu drive.
