### ISSUE TITLE
How to train PromptPAR using our own dataset

### ISSUE THREAD

**Issue by VisImage** [Event-AHU/OpenPAR#24]
Thank you for sharing the code, but how to train PromptPAR using our own dataset?

**Comment by 1125178969** [comment]
You can refer to the code in /dataset/prepocess to generate pkl files of your own dataset for training. Just include the image path and onehot tag

**Comment by VisImage** [comment]
Thanks for reply. There are more than 10 files in the folder.  Not clear which file (or files) I need to read to get our own dataset?

**Comment by 1125178969** [comment]
You can refer to pa100k.py because he is simple enough, you just need to modify **attr_words**, **pa100k_data (annotation file)** to your own dataset.

**Comment by VisImage** [comment]
Thank for the reply. but I am not able to find the file pa100k.py in the folder /dataset/preprocess as you indicated.  the files in the folder are listed below. Please let me know if that is the right folder. Thank you


![OpenPAR_VTFPR++_dataset_preprocess](https://github.com/user-attachments/assets/92f941a4-86fb-43e4-8d79-9f08cd1b9bbc)
![idea](https://github.com/user-attachments/assets/4c4b0042-1875-4d2f-8538-2a4abd187034)

**Comment by 1125178969** [comment]
you can find it in PromptPAR
