### ISSUE TITLE
Requesting Google Drive Download link for pre-trained models

### ISSUE THREAD

**Issue by Nouman945** [Event-AHU/OpenPAR#25]
Hi, I tried to download the checkpoints from the baidu drive here,

https://pan.baidu.com/s/196CDyMFX5rrMQEcC4kQ00w#list/path=%2FPromptPAR_ckpts

But I wasn't able to do so. It's even not allowing to create a new account probably because of my location. Can you please provide a Google Drive link to download the model files please. I want to test the model

**Comment by 1125178969** [comment]
Thanks for following our work, we've just updated the Google Drive link!

**Comment by Nouman945** [comment]
> Thanks for following our work, we've just updated the Google Drive link!

Hi, Thanks for sharing the checkpoint file I really appreciate it. I am trying to run the test_example.py and there are issues with a import. specifically.

from models.test_base import * file test_base is not present in the models directory.

**Comment by 1125178969** [comment]
The test_example.py uploaded at the time was just an example used to demonstrate loading the model, we've updated it now.

**Comment by Nouman945** [comment]
Thankyou @1125178969. Working now. Do you have a sample script to test the model on a single image?  And are there any specific instructions to get this file?

```FileNotFoundError: [Errno 2] No such file or directory: '/data/jinjiandong/datasets/PETA/pad.pkl'

**Comment by 1125178969** [comment]
You can use ‘. /dataset/preprocess’ in peta_pad.py to generate the pkl file

**Comment by Nouman945** [comment]
That file is giving this error. 

```
FileNotFoundError: [Errno 2] No such file or directory: '/data/jinjiandong/datasets/PETA/PETA.mat'
```

**Comment by Nouman945** [comment]
@1125178969  can we connect?

**Comment by 1125178969** [comment]
You can give me your email and I'll send it to you.

**Comment by Nouman945** [comment]
> You can give me your email and I'll send it to you.

muhmmadnouman945 @ gmail . com

**Comment by Herry-CN** [comment]
我是一位PAR的爱好者，我也需要一份.mat文件。12912697@qq.com
