### ISSUE TITLE
Dataset MSP60k zip file is damage from google drive 

### ISSUE THREAD

**Issue by asad1416** [Event-AHU/OpenPAR#26]
I was trying to download the Dataset from Google drive link, but when I try to unzip the file I am getting error that this zip file is damaged. Please guide or share any other link from where I can download this dataset.

**Comment by 1125178969** [comment]
We update the link to https://drive.google.com/file/d/1KBHFPJHtY6V-XrdLo3r-s2I6aDvWoTz4/view?usp=sharing

**Comment by asad1416** [comment]
Dear sir
I hope you are doing well, I am trying to train bench mark model using this
dataset  but it say some .pkl file is missing which I have to put in
configuration file. Because I tried to put dataset_random.pkl but it gives
error no key with sentences . I figure out somehow I have to generate some
files . But not it is asking base.pkl file which i can not find anywhere .

Please guide me in this matter, I shall be grateful to you for your help.
