### ISSUE TITLE
How to get Prediction on a single image. using Promptpar

### ISSUE THREAD

**Issue by asad1416** [Event-AHU/OpenPAR#27]
I am trying to get prediction on a single image, test_example.py is running but I could not find model.predict funciton. Can you please guide me how I can get prediction in the form of attributes or token and how we can get a sentence like output.

**Comment by 1125178969** [comment]
You can perform a forward pass and then **sigmoid** the model's predictions, and then output the index of the corresponding attribute list through **threshold judgment**
