### ISSUE TITLE
Question of loss NaN for LLM-PAR

### ISSUE THREAD

**Issue by GWwangshuo** [Event-AHU/OpenPAR#31]
After running the following command:

`python train.py --dataset PETA --exp expname`

I encountered an issue where the loss value became NaN, as shown in the image below:

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/0ecac31c-380e-4902-9653-775b32e7a8eb">

Could you please help me solve this?

**Comment by 1125178969** [comment]
Did you change the language model from Vicuna-7B to LLAMA-2?

**Comment by 1125178969** [comment]
You should change the language model to Vicuna-7b.

**Comment by GWwangshuo** [comment]
Thank you for getting back to me so quickly. Regarding the language model, I am using Vicuna-7b. Please provide further guidance on how to resolve this issue.

<img width="1504" alt="image" src="https://github.com/user-attachments/assets/3d8b841c-479e-4b07-9959-0635b9f84394">

**Comment by 1125178969** [comment]
The correct LLM has 33 sub-models in our work, I found it only 2 in your logs

**Comment by GWwangshuo** [comment]
Which one do you use here? The first one?

<img width="934" alt="image" src="https://github.com/user-attachments/assets/3274a0d2-d45e-45e6-9f6c-4a3f1725cfa1">

**Comment by 1125178969** [comment]
you can get from [lmsys/vicuna-7b-delta-v1.1](https://huggingface.co/lmsys/vicuna-7b-delta-v1.1)

**Comment by 1125178969** [comment]
If you still can't train try converting the model via this script [conversion](https://huggingface.co/docs/transformers/main/model_doc/llama) and [script](https://github.com/huggingface/transformers/ blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py )

**Comment by GWwangshuo** [comment]
> you can get from [lmsys/vicuna-7b-delta-v1.1](https://huggingface.co/lmsys/vicuna-7b-delta-v1.1)

Thank you for clarifying the LLM resources; everything is working now. Since I've resolved this issue, I'll go ahead and close it.
