### ISSUE TITLE
about the visual_encoder

### ISSUE THREAD

**Issue by Dinosaurcubs** [Event-AHU/OpenPAR#4]
Ncie work, congratulations! I got a question recently, it seems you  removed the last ln_post layer before the projection layer in the visual_encoder， What is the reason for doing this?

**Comment by 1125178969** [comment]
We will feed the visual features of CLIP to the multimodal encoder for feature fusion, so we think that the LN here is not necessary, but experiments show that with or without this LN has no effect on the results.

**Comment by Dinosaurcubs** [comment]
got it, thanks!
