### ISSUE TITLE
Accuracy and F1 score when using ViT-base

### ISSUE THREAD

**Issue by MINDYEOI** [Event-AHU/OpenPAR#5]
Hi. Thank you for sharing your great work.

I wonder how much is the mA and F1 score if SequencePAR and PromptPAR backbone is changed into ViT-b/16 on PA100k, PETA, RAPv2 dataset.
If you conducted the experiments, could you kindly share in public?

Thank you.

**Comment by 1125178969** [comment]
Sorry, we have not experimented with replacing the backbone on more datasets, if you are interested, you can try to reproduce the code for your experiments, or we will update these results later!

**Comment by MINDYEOI** [comment]
Thank you :)
