### ISSUE TITLE
Can you release pre-trained models?

### ISSUE THREAD

**Issue by floriyellin** [Event-AHU/OpenPAR#6]
Thank you for your code.  Are your pre-trained models available for downloading?  Thanks!

**Comment by wangxiao5791509** [comment]
@floriyellin  Hi, the pre-trained model will be released soon. After the Spring Festival.

**Comment by 1125178969** [comment]
We will be updating the checkpoints for all datasets in the near future.

**Comment by rose-jinyang** [comment]
Hello
When will you upload all the trained checkpoints?

**Comment by 1125178969** [comment]
We have updated the checkpoint information for the relevant datasets
