### ISSUE TITLE
WIDER split images

### ISSUE THREAD

**Issue by MINDYEOI** [Event-AHU/OpenPAR#7]
Hi!
I wonder how can I get `split images` on WIDER dataset.
The dataset I have is not cropped.

Thank you for sharing your great work!

**Comment by 1125178969** [comment]
You can get split images and corresponding annotations from https://drive.google.com/drive/folders/1f0CH-H5V_Ej-rJu_pRQJJiktdbJLv58M?usp=sharing.

**Comment by MINDYEOI** [comment]
Thank you!
